2025-04-02 16:12:07,379 ERROR: Exception on /students/67ed61c56f1e2a63a3f8c91c/delete [PUT] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\routes\students.py", line 204, in flag_student_left
    student.payments.agreed_payments = student.payments.real_payments.copy()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RealPayments' object has no attribute 'copy'
2025-04-02 16:22:55,472 ERROR: Exception on /students/67ed61c56f1e2a63a3f8c91c/delete [PUT] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\routes\students.py", line 204, in flag_student_left
    real_payments_dict = { key: value for key, value in student.payments.real_payments._data.items() if not key.startswith('_') }
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RealPayments' object has no attribute 'copy'
2025-04-02 16:24:22,961 INFO: GSP Finance Backend Startup [in C:\Users\desktop\Desktop\gspFinance\gspfinanceback\app.py:36]
2025-04-02 16:26:05,999 INFO: GSP Finance Backend Startup [in C:\Users\desktop\Desktop\gspFinance\gspfinanceback\app.py:36]
2025-04-02 16:26:14,696 ERROR: Exception on /students/67ed61c56f1e2a63a3f8c91c/delete [PUT] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\routes\students.py", line 210, in flag_student_left
    student.save()
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\document.py", line 422, in save
    self.validate(clean=clean)
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\base\document.py", line 440, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Student:67ed61c56f1e2a63a3f8c91c) (agreed_payments.Invalid embedded document instance provided to an EmbeddedDocumentField: ['payments'])
2025-04-02 16:26:52,079 ERROR: Exception on /students/67ed61c56f1e2a63a3f8c91c/delete [PUT] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\routes\students.py", line 210, in flag_student_left
    student.save()
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\document.py", line 422, in save
    self.validate(clean=clean)
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\base\document.py", line 440, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Student:67ed61c56f1e2a63a3f8c91c) (agreed_payments.Invalid embedded document instance provided to an EmbeddedDocumentField: ['payments'])
2025-04-02 16:29:23,941 ERROR: Exception on /students/67ed61c56f1e2a63a3f8c91c/delete [PUT] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\routes\students.py", line 210, in flag_student_left
    student.save()
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\document.py", line 422, in save
    self.validate(clean=clean)
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\mongoengine\base\document.py", line 440, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Student:67ed61c56f1e2a63a3f8c91c) (agreed_payments.Invalid embedded document instance provided to an EmbeddedDocumentField: ['payments'])
2025-04-02 16:30:48,406 INFO: GSP Finance Backend Startup [in C:\Users\desktop\Desktop\gspFinance\gspfinanceback\app.py:36]
